# Generated by Django 5.2 on 2026-02-20 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alomind', '0002_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='datetime',
        ),
        migrations.AddField(
            model_name='medicines',
            name='isAfternoon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicines',
            name='isEvening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicines',
            name='isMorning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicines',
            name='isNight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alomind.gallery'),
        ),
    ]
