# Generated by Django 5.2 on 2026-02-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alomind', '0003_remove_gallery_datetime_medicines_isafternoon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tasks_images/'),
        ),
    ]
