# Generated by Django 5.2 on 2026-02-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alomind', '0005_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
