# Generated by Django 5.2 on 2026-02-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alomind', '0006_history_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='image',
        ),
        migrations.AddField(
            model_name='history',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='history',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='medical_history/'),
        ),
    ]
