# Generated by Django 5.2 on 2026-03-02 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alomind', '0007_remove_history_image_history_ai_summary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='datetime',
        ),
        migrations.AddField(
            model_name='tasks',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ScheduledMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dosage', models.CharField(max_length=255)),
                ('isMorning', models.BooleanField(default=False)),
                ('isAfternoon', models.BooleanField(default=False)),
                ('isEvening', models.BooleanField(default=False)),
                ('isNight', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_med', to='alomind.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TimedMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dosage', models.CharField(max_length=255)),
                ('time_gap', models.CharField(max_length=255)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timed_med', to='alomind.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Medicines',
        ),
    ]
