# Generated by Django 5.2 on 2026-03-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alomind', '0008_remove_tasks_datetime_tasks_date_tasks_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
