# Generated by Django 5.2 on 2026-03-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alomind', '0009_history_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmed',
            name='food',
            field=models.BooleanField(default=False),
        ),
    ]
