# Generated by Django 5.2 on 2026-03-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alomind', '0010_scheduledmed_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='afternoon_med',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='alarm',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='evening_med',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='morning_med',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='night_med',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
