# Generated by Django 5.2 on 2026-03-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alomind', '0011_patient_afternoon_med_patient_alarm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
