# Generated by Django 5.2 on 2026-03-16 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alomind', '0012_caregiver_profile_pic_patient_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='music/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music', to='alomind.patient')),
            ],
        ),
    ]
